config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'logins#snew'

  get '/login', to: 'logins#snew'
  post '/login', to: 'logins#screate'
  get '/logout', to: 'logins#sdestroy'

  get '/summary/logout', to: 'logins#sdestroy'
  get '/summary/login', to: 'logins#snew'
  post '/summary/login', to: 'logins#screate'

  get '/typeform', to: 'welcome#typeformget'
  post '/typeform', to: 'welcome#typeformpost'

  post '/rsvp', to: 'welcome#rsvppost'

  # get '/seu', to: 'welcome#seu'
  # post '/seu', to: 'welcome#pcsv'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; <a href="https://github.com/weirdindiankid" target="_blank">weirdindiankid 2018</a></p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<!-- <%= link_to "Spark X-Lab", "/", class: "btn btn-lg btn-success", id: "logo" %> -->
		<%=image_tag("../../app/assets/images/techtogether-logo.png", id:"techtogether-nav-logo")%>

		 <% if logged_in? %>
      <!--div class="nav_item">
        <%= link_to "New Event", 'events', class: "btn btn-default btn-warning" %>
      </div-->
      <ul class="nav_item pull-right">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-primary dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class='dropdown-menu'>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="nav_item pull-right">
        <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
      </div>
    <% end %>
	</div>
</header>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechTogether Teammate Matching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>